### ISSUE TITLE
Repeatedly performing npm-install fails with EISGIT: Appears to be a git repo or submodule

### ISSUE THREAD

**Issue by ccorneliusHsv** [carnivalmobile/carnival-sdk-react-native#38] opened 2019-10-17 14:20 UTC
If I run npm install again, it displays an error for EISGIT. Looks like there is a file that needs to be ignored. Here is a link to the exact same issue on another project. 

https://github.com/APSL/react-native-version-number/issues/13 

solutions appears to be add a .npmignore file and add .git to it.

**Comment by igstewart3** [comment] 2019-11-04 00:50
I've managed to recreate this issue and that solution looks like it should resolve it. Thanks for reporting it! I should be able to get a fix out shortly.

**Comment by ccorneliusHsv** [comment] 2019-11-04 13:47
Thanks for the update. Looking forward to the fix!

**Comment by igstewart3** [comment] 2019-11-14 03:47
Confirmed fixed in release 3.3.1.

**Closed by igstewart3** 2019-11-14 03:47 UTC
